commitish: main
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🤖 Dependabot'
    label: 'dependencies'
  - title: '🚀 Features'
    label: 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'      
  - title: '🎉 Release'
    labels: 
      - 'release'
      - 'hotfix'  
exclude-labels:
  - 'skip-changelog'
template: |
  ## Changes

  $CHANGES
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
      - 'feature'
  patch:
    labels:
      - 'patch'
  default: patch