name: Post Release

on:
  release:
    types: [published]

jobs:
  post-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2        
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: |         
         yarn install
         yarn test         
         git config --global user.name "$USER"
         git config --global user.email "$USER@users.noreply.github.com"         
         yarn version --no-git-tag-version --no-commit-hooks --new-version $TAG
         git add .
         git commit -m "updated version to $TAG"        
         git push origin HEAD:main
         git push origin -f HEAD:$TAG
        env:
         TAG: ${{ github.event.release.tag_name }}
         USER: ${{ github.event.repository.owner.login }}
      